- bridge_track.c
I got these messages due to a switch + phy driver bug.
But it makes sense to have these a bit more explicit for
future cases.
> bridge_track: add verbose debug messages in bridge_bpdu_rcv()

- bridge-stp.in
It happens that the background job to add the bridge running to early before the parent shell actually exits. The msptctl call is failing then and STP mode is turned off.
Add a sleep 1 as a workaround.
(Happened to me almost every time during booting of a device running mstpd on OpenWrt.)
> bridge-stp.in: add a sleep to the mstpctl background workaround

- debian/mstpd.lintian-overrides
utils/mstpctl-utils-functions.sh is a bash library, so it is not
supposed to be ran individually. It has a shebang as it was
recommended by shellcheck, so Lintian generates a false positive.
Override it.
> debian: add override for script-not-executable LW

- .travis.yml
Adapted from: http://travis.debian.net/
@bluca
https://travis-ci.org/commodo/mstpd/builds/233154741
AFAICT, the build looks passing ; 
tho, the lintian checks/warnings did not produce a build failure
not sure if they should
```
warning: the authors of lintian do not recommend running it with root privileges!
W: mstpd: binary-without-manpage sbin/bridge-stp
W: mstpd: binary-without-manpage sbin/mstp_restart
W: mstpd: binary-without-manpage sbin/mstpd
W: mstpd: script-not-executable lib/mstpctl-utils/mstpctl-utils-functions.sh
```
I don't get why the warning `warning: the authors of lintian do not recommend running it with root privileges!`
maybe that's caused by the fact that it's run in docker
> build,travis: add support for debian's travis script

- bridge-stp.in
A re-spin of https://github.com/mstpd/mstpd/pull/37.
This change checks if the config_cmd is executable,
or checks if the command is in the PATH env var.
I referenced the `type` command from an OpenWrt script.
Hopefully that would ensure that it's portable enough
across other shells as well.
Seems to work on bash & zsh too.
> bridge-stp.in: test config_cmd for executability

- Makefile.am
This fix yocto out of tree build using autotools.
Change-Id: Idf854cfd7dda262d98b461bc9df6a69bc619b942
Signed-off-by: Gerson Fernando Budke <gerson.budke@intelbras.com.br>
> Makefile.am: Fix install-data-hook for out of tree build

- ctl_main.c
GCC 7 caught this:
```
ctl_main.c: In function 'isbridge':
ctl_main.c:283:25: error: '%s' directive output may be truncated writing up to 255 bytes into a region of size 241 [-Werror=format-truncation=]
^
ctl_main.c:293:36: note: in expansion of macro 'SYSFS_CLASS_NET'
snprintf(path, SYSFS_PATH_MAX, SYSFS_CLASS_NET "/%s/bridge",
^~~~~~~~~~~~~~~
ctl_main.c:705:50: note: format string is defined here
snprintf(buf, sizeof(buf), SYSFS_CLASS_NET "/%s/brif", br_ifname);
^~
In file included from /usr/include/stdio.h:938:0,
from log.h:30,
from ctl_main.c:35:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output between 23 and 278 bytes into a destination of size 256
return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1, …
```
> ctl_main: fix truncation warnings/errors caught by GCC 7

- brmon.c
A pointer was dereferenced before the message length was validated.
Very minor and extremely unlikely to happen in practice.
> dump_msg: Avoid possible invalid pointer dereference in case of erronous message

- brmon.c
Since the data is padded with zeroes to 4-byte boundaries it effectively worked on little endian machines, although unless I'm missing something it wouldn't work at all on big endian platforms.
https://github.com/torvalds/linux/blob/50c4c4e268a2d7a3e58ebb698ac74da0de40ae36/net/core/rtnetlink.c#L1555
I suspect it might also create an out-of bound access if this is the last entry in the buffer (since the payload is only one byte). This is rather unlikely however.
> Correct the payload type of IFLA_OPERSTATE from int to __u8

- bridge_track.c
Previously both the pre- and post-state variables were set to one
another before the message was printed.
> set_br_up: fix info message to actually show the transition

- mstp.c
It's what most people seem to use.
And we do report it as being compliant with IXIA ANVL RSTP
test suite.
So, might as well default to RSTP and use mstpctl to
change to MSTP.
> mstp.c: default to rstp proto level

- main.c
On issuing a /sbin/mstp_restart command the daemon would occasionally
fail with "error, server_socket: Couldn't bind socket: Address already
in use".
On termination explicitly close the server socket
(ctl_socket_cleanup()).
> Close control socket on termination

- .travis.yml
Not sure which is the default distro in Travis CI at the moment.
But, it allows the use of Ubuntu Xenial (16.04 which is great because
that's pretty recent compared to Trusty (14.04) or Precise (12.04)
> .travis.yml: switch to Ubuntu Xenial distro for testing

- main.c
Rearrange the startup sequence so that the command line arguments are
processed first followed by the opening of the syslog connection. In
this way the initial self-check sequence (and version number) gets
pushed out to syslog.
In addition include the PID in syslog messages:
mstpd[21648]: main: Version - 0.0.6-
mstpd[21648]: main: Sanity checks succeeded
> Rearrange the startup sequence

- bridge-stp.in
- bridge_track.c
When STP is turned off on an interface, check all other bridge/switch
instances to see if user-mode STP is enabled. Only terminate the
daemon (SIGTERM) if there are no other bridge/switch interfaces in use
by the daemon.
> Check STP state before terminating MSTPd

- ctl_main.c
Added JSON output format for all available show commands:
- showbridge
- showmstilist
- showmstconfid
- showvid2fid
- showfid2mstid
- showport
- showportdetail
- showtree
- showtreeport
- showmstconfid
This feature is very useful when we need obtain parsed data from mstpd.
For example, we can obtain JSON data in CGI script and transfer it
to the client's web browser for further analysis or/and display.
Output format can be selected by -f <format> (--format=<format>) command
line option. Currently available formats:
- plain : plain text (used by default)
- json  : JSON
Signed-off-by: Anton Kikin <a.kikin@tano-systems.com>
> ctl_main: Add JSON output format support

- main.c
In most cases, that file-pointer and descriptor will be released since the
app terminates.
However, it's good practice to free it before doing that.
> main.c: free file pointer when exiting

- ctl_main.c
- mstp.c
- mstp.h
- utils/bash_completion
- utils/ifupdown.sh.in
- utils/mstpctl-utils-interfaces.5
- utils/mstpctl.8
Add support for a "BPDU Port Filter" option ("setportbpdufilter"),
i.e. discard BPDUs on ingress and do not issue BPDUs. Further add a
counter that indicates the number of received BPDUs that have been
discarded.
> Disable STP processing on a specific port

- ctl_main.c
Fixes #4 
Changeset implements batch command processing.
This can be specified via stdin (with -s / --stdin CLI specifier) or from file (with -b / --batch <file> ).
By default processing is done until the first failing or invalid command is found.
A  -i / --ignore option can be provided to skip faulty commands ; this can be useful in teardown cases.
For batch-files, they are validated first to check if there are any invalid commands/typos, but these will be ignored if `--ignore` is provided.
For stdin, all batch commands willl be processed until the first failing; depending on whether `--ignore` is provided, processing will stop or continue.
> mstpctl: implement batch command processing

- mstp.c
- netif_utils.c
strncpy() is not safe as it can put `len` elements of a string and discard
the null-char if there isn't any room left.
An alternative option would be to use `strlcpy()` but that function may not
be portable to all libc implementations.
So, just reduce the `len` by 1 byte to allow room for null-char.
This was reported via string-fortify headers.
> treewide: allow room for null-char in strncpy()

- rpm.spec
- utils/ifquery
`utils/ifquery` is used by rpm.spec for mstpd configuration on RPM-based systems.  `rpmbuild` now requires all python shebangs to be versioned ("python2" or "python3").
While I'm changing things in that file, the `flake8` python linter complains about some minor formatting issues, so I've cleaned those up.
> ifquery: Use versioned python shebang and fix flake8 warnings

- .gitignore
- Makefile.am
- configure.ac
- utils/mstpd.service.in
This is a proposition to add a systemd unit. I still needs to test it (too late now).
Related to Debian, I would suggest Debian ships `/etc/bridge-stp.conf` with `MANAGE_STPD` sets to `n`.
> Add systemd unit file

- Makefile.am
The final service file is output into the build directory, not the source directory
> Copy the system unit build artifact from the build folder

- Makefile.am
This change disables the -Werror flag under normal build. When updating
compilers, new warnings get enabled by default.
We will do this only during CI where the --enable-devel flag will be set.
> build: move -Werror flag under --enable-devel opt

- Makefile.am
* Every distro and package manager uses different compression for
man pages.
> Don't compress man pages

- libnetlink.c
- libnetlink.h
As requested in #112, these two patches that come from #103 can already be applied to support any future solution and experiments in setting the state for either a VLAN or an MSTI in Linux.
> libnetlink changes required for any VLAN/MSTI state solution

- libnetlink.h
The header file uses certain data types for which it doesn't include
header files and relies and the source code to provie them.
This is required for the use of libnetlink.h in #112.
> make libnetlink.h standalone

- rpm.spec
- utils/ifquery
* python2 is not maintained anymore and all scripts using it should be
updated to python3
* ran 2to3 for utils/ifquery and added python3 shebang
* removed python3 sed from rpm.spec
Signed-off-by: Jan Klare <jan.klare@bisdn.de>
> utils/ifquery: drop python2 support

- .github/workflows/build.yml
- .gitignore
- Makefile.am
- rpm.spec
Updated Makefile.am to allow the make distcheck to work, which
means make install can be reversed by make uninstall, and
make clean correctly removes generated files.  make dist now
also creates a tarfile that can be used to configure and
build from.  Added README to install.
Signed-off-by: Scott Shambarger <devel@shambarger.net>
> make: Updated Makefile.am to support distcheck

- Makefile.am
- bridge-stp.in
- utils/ifupdown.sh.in
- utils/mstp_config_bridge.in
- utils/mstpctl.8
As brctl is deprecated in many distributions (and removed in
CentOS 8 Stream), this patch replaces it with the equivalent
ip/bridge commands from iproute2 (already required).
The patch also handles a race with spawning mstpd, corrects
killing it (Fixes #122), and has bridge-stp log errors to
syslog (if possible, as stderr is not logged).
Also fixes handling of pre-up etc in interfaces parsing.
Signed-off-by: Scott Shambarger <devel@shambarger.net>
> Closes #123 - Replace brctl with ip and bridge commands

- .gitignore
- Makefile.am
- mstpd.spec
- utils/ifquery
- utils/mstpd.service.in
- utils/nm-dispatcher.in
This patch fixes rpmbuild/mock failures due to missing BuildRequires,
and references to absolute filenames during install.  In addition
it corrects the quoting of the bridge-stp file contents, and
correct several macro references.
Now mock builds correctly on Fedora/CoreOS etc
Signed-off-by: Scott Shambarger <devel@shambarger.net>
> rpm.spec: Fix mock build, requires and quoting

- Makefile.am
- configure.ac
The current setup with the ifupdown scripts, is that they get installed if
the system that builds mstpd is a Debian system.
When building for Debian on another host, or cross-compiling via Yocto or
some other build-system, this can be problematic as the host-system can be
different, so we cannot rely on the fact that the ifupdown package is
present on the target system.
So, the option is to enable the installation of MSTPD's ifupdown scripts
via a configure flag.
Initially this was discussed that this should be a
`--disable-ifupdown-scripts`, but this seems problematic as the only place
where this is needed is for Debian/Ubuntu systems.
Also, ifupdown seems to be going away from Debian as default, so maybe the
a --enable-install-ifupdown-scripts options is better.
Fixes: #126 …
> build: add option to enable installation of ifupdown scripts

- ctl_main.c
as I need to print some information(including enabled, port-id, internal-port-cost, state, role, admin-edge-port) for all of my interface(about 45 interfaces) use of showport command doesn't optimal(45*6 mstpdctl binary exec in my script). with showportparams command that will be add in this MR we can probe over than one parameter for an interface.
these changes will be useful for any one with my problem.
> mstpctl: add showportparams cmd

- bridge-stp.in
Reported via: https://github.com/mstpd/mstpd/issues/134
```
bridge-stp script calls logger with the full options --tag and --stderr
BusyBox only supports the shorthand of the options -t and -s respectively.
The shorthands should also work on non-busybox systems.
https://elixir.bootlin.com/busybox/1.35.0/source/sysklogd/logger.c
https://man7.org/linux/man-pages/man1/logger.1.html
```
> bridge-stp.in: use short-hand arguments for logger command

- bridge-stp.in
Busybox uses a version of pdiof that doesn't support the -c option. As
such, this renders mstpd non-functional on any Busybox system.
Add detection for this, and adjust the pidof command at runtime.
> bridge-stp.in: support different versions of pidof

- utils/mstpctl-utils-functions.sh
Fix the following shellcheck warnings:
```
In utils/mstpctl-utils-functions.sh line 5:
while [ x"${1+set}" = xset ]
^---------^ SC2268 (style): Avoid x-prefix in comparisons as it no longer serves a purpose.
Did you mean:
while [ "${1+set}" = set ]
In utils/mstpctl-utils-functions.sh line 53:
echo $i
^-- SC2086 (info): Double quote to prevent globbing and word splitting.
Did you mean:
echo "$i"
```
> mstpctl-utils-functions.sh: fix shellcheck warnings

- netif_utils.c
ethtool_cmd.speed is a 16 bit value, so the highest representable speed is 65.535 MB/s. For higher speeds, the upper bits are stored in cmd.speed_hi.
But since mstpd was only looking at speed, effectively the speed used was modulo 65536. This broke cost calculation, as a 200G link was now considered a 34.4G link, so its cost rose from expected 100 to 580.
Fix this by using the provided helper, ethtool_cmd_speed().
> netif_utils: fix speeds > 65G
